version: 2
updates:
  - package-ecosystem: "npm" 
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" 
    directory: "/example" 
    schedule:
      interval: "monthly"
