language: node_js
node_js:
  - 14
  - 12
  - 10
  - 8
cache:
  directories:
    - node_modules
before_install:
  - npm install -g codecov
jobs:
include:
  - stage: test
    script:
      - npm run test && codecov
